spring:
    profiles: prod
service:
  message: Prod profile
spring:
  datasource:
    driver: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/testing_tool_prod?useUnicode=true&characterEncoding=utf-8&createDatabaseIfNotExist=true
    username: root
    password: root
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master-prod.yaml